[package]
name = "ohmycine-player"
version = "0.1.7"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
libmpv-sys = "3.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["sync", "time"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tonic = { version = "0.12", features = ["tls-native-roots"] }
prost = "0.13"
prost-types = "0.13"
tauri-plugin-dialog = "2"
sha2 = "0.10"
sha1 = "0.10"
md5 = "0.7"
rusqlite = { version = "0.32", features = ["bundled"] }
aes-gcm = "0.10"
base64 = "0.22"
flate2 = "1"
roxmltree = "0.20"
rand = "0.8"
raw-window-handle = "0.6"
notify = "6.1"
tauri-plugin-updater = "2.10.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_Security_Cryptography",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging",
] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
